### ISSUE TITLE
组件写的不错

### ISSUE THREAD

**Issue by kaoding** [martSforever/plain-ui#1]
**这是从oschina上看到你写的**
**职业规划** 
按照我自己的计划，这套组件库还差一些组件或者功能还没有做完，等做完之后，我的下一步计划还有很多，但是不知道该做那个，那个才能够提高我的技术能力。

1. 开发一个React版本的组件库，功能与目前Vue实现的PlainUI类似，只是单纯想提高自己的React水平，但是在不换工作的前提下，我这边基本没有接触React项目的可能。

2. 基于Vue开发移动App组件库，没错，又是一个轮子。可是这个轮子跟市面上的也有一点区别，我观察了不少Vue移动端的组件库，发现好像没有提供页面导航之类的功能，应该都是想着VueRouter就能够搞定了，不知道是不是我对VueRouter的理解不到位，我感觉VueRouter实在是很难处理类似App上页面前进后退的功能，我想着是自己开发一个页面导航的组件，然后以这个为基础封装其他的基础组件或者服务，顺便提高自己的移动App开发能力；

3. 接外包。虽然工作很忙，但是目前的工作已经很难再让我的技能得到提升，我没有接过私活，不晓得接私活能不能提高自己的技术实力，或者说项目应对能力，但是目前一直苦于找不到比较靠谱的外包项目。

4. 还有一个，就是我以前非常喜欢在慕课上看实战视频（不是在打广告啊），现在差不多写完这套组件库之后，我有打算录制一个专门开发组件库的视频（目前上面好像没有专门讲解组件库的视频），不知道这个可不可行。

**Comment by kaoding** [comment]
1. 你现在vue很熟悉，react不算太熟悉，现在的组件是使用vue写的，如果想这套组件能让更多人使用上，先别急的用react来实现这套组件，先把vue这套组件稳定了和丰富了，不断推动让更多人使用上。移动APP组件库也先不急的写（一个人的时间总有限的）。
2. 接外包这事，不仅是代码能力提升，还有其它方面能力的提升，根据自己的情况来安排。
3. 能讲课这个能力比定组件库要求更高，还可以挣到钱，当然是最好的。

**Comment by kaoding** [comment]
@martSforever 我有react的兼职项目可做， lijiehua@mukuit.com

**Comment by martSforever** [comment]
非常谢谢，因为最近在面试嘛，希望能够集中精力准备好面试所需要的知识，所以最近是在复习看文档，巩固自己的前端基础知识。等面试结束之后，我再继续完善这个组件库，然后继续下一步规划。非常感谢您的建议。
