### ISSUE TITLE
会出文档吗 ？

### ISSUE THREAD

**Issue by geLouTingFengSheng** [martSforever/plain-ui#2]
我看你这套组件好像只有演示，没有有看到对应文档，不知道是我没找到还是怎么的

**Comment by martSforever** [comment]
哈喽，每个示例右上角有可以看示例代码，以及在线调试的功能

**Comment by martSforever** [comment]
是两个图标

**Comment by martSforever** [comment]
最新版的组件库是基于ts+composition api开发的，开没有开发完，所以还没写文档和示例，等写完了就准备写了
